#!/bin/sh
#bug fix for container restart
(rm /run/rsyslog.pid | true)

chmod 777 -R /usr/local/share/clamav/
if [ ! -f /usr/local/share/clamav/bytecode.cvd ]
then
#first run - get full virus databases
  freshclam
fi
freshclam -d -c 24
clamd
